### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by d4ndo** [TheLastProject/PyPass#1]
Could you provide some more information about the dependencies.

I get the following error message:

ImportError: No module named queue

cheers.

**Comment by TheLastProject** [comment]
I do need to get to documenting the dependencies properly, when I find the time.

Regarding this issue, queue is built into Python, but only into Python 3. Have you tried starting PyPass with Python 3 instead of Python 2?

**Comment by d4ndo** [comment]
Thx you.

python3 seems to solve the queue issue.  (>= python3)

Now I get this message:

QQmlApplicationEngine failed to load component 
file:///PyPass/main.qml:21 module "QtQuick.Window" is not installed
file:///PyPass/main.qml:18 module "QtQuick" is not installed
file:///PyPass/main.qml:21 module "QtQuick.Window" is not installed
file:////PyPass/main.qml:18 module "QtQuick" is not installed

But python3-pyqt5.qtquick is installed. Maybe i have to set some ENVIRONMENT variable.

**Comment by TheLastProject** [comment]
pyqt5 is only a wrapper for qt5, so it needs Qt5 as well. You have a subset of those installed, but not all of them.

Honestly, I'm not sure which Qt5 packages it needs exactly. I'll hopefully be able to try and figure out with a clean Debian install in some days.

However, if you want to try PyPass now, you'll probably have to keep installing Qt5 packages until it works. If you decide to go this route, I'd very much appreciate it if you could give me the list of the packages you did install and the OS you're running, so I could write a dependency list.

**Comment by Taknamay** [comment]
I couldn't get it to run, but these packages helped on Ubuntu 14.04:

python3-pyqt5
python3-pyqt5.qtquick
python3-pexpect
python3-pyinotify
libqt5qml-quickcontrols
qtdeclarative5-window-plugin
qtdeclarative5-qtquick2-plugin

**Comment by TheLastProject** [comment]
I can confirm that you do need to install:
  python3-pyqt5
  python3-pyqt5.qtquick
  python3-pexpect
  python3-pyinotify

The other Qt dependencies seemed to come with the KDE Plasma 5 desktop, so currently I'm still not sure what else to install, sorry. I'm going to leave this open in the hope someone comes along who can (help) figure out the exact dependencies.

**Comment by TheLastProject** [comment]
On a basic Debian Testing machine I have been able to get PyPass working by installing the dependencies I have added in d76563fc44fe91283f820057fb06e8fb9a7aeeab. These should probably work for Debian Stable too.

A list for other distributions is welcome, but for now, I'll consider this issue fixed.
